"""create tables

Revision ID: 435e907f6a0f
Revises: 4931afb902f6
Create Date: 2025-10-15 12:27:39.323782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435e907f6a0f'
down_revision: Union[str, Sequence[str], None] = '4931afb902f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_localities_city_name'), 'localities', ['city_name'], unique=False)
    op.create_index(op.f('ix_localities_country_name'), 'localities', ['country_name'], unique=False)
    op.create_index(op.f('ix_localities_id'), 'localities', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('locality_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locality_id'], ['localities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_localities_id'), table_name='localities')
    op.drop_index(op.f('ix_localities_country_name'), table_name='localities')
    op.drop_index(op.f('ix_localities_city_name'), table_name='localities')
    op.drop_table('localities')
    # ### end Alembic commands ###
